### ISSUE TITLE
Time for a new release on OPAM?

### ISSUE THREAD

**Issue by yminsky** [pqwy/notty#16]
The version on opam is pretty old at this point, and is not compatible with the most recent uutf. It's possible to build without downgrading by pinning to the dev version, but making a release and putting it on opam would be lovely.

**Comment by pqwy** [comment]
Yeah, long overdue. Sometimes I keep on chasing _this one more detail_ before making a release. Sometimes that drags on. And sometimes I completely drop the ball.

Just pushed a release out. Thanks for the prod!
