### ISSUE TITLE
Notty is incompatible with OCaml 4.06

### ISSUE THREAD

**Issue by gasche** [pqwy/notty#17]
There was a breaking change to the Format library in 4.06

```
* GPR#615: Format, add symbolic formatters that output symbolic
  pretty-printing items. New fields have been added to the
  formatter_out_functions record, thus this change will break any code building
  such record from scratch.
  (Richard Bonichon and Pierre Weis, review by Alain Frisch)
```

notty appears to be affected, according to the logs of my opam-builder instance:

```
/home/barsac/scherer/opam-builder/4.06.0+beta2+default-unsafe-string/.opam/4.06.0+beta2+default-unsafe-string/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -w A-4-33-40-41-42-43-34-44-48 -package uutf -package uuseg -package uucp -package result -I src -o src/notty.cmo src/notty.ml
File "src/notty.ml", line 508, characters 41-99:
Error: Some record fields are undefined: out_indent
```

Would you consider making a release that is compatible with 4.06? (If you have pending features, it would probably make sense to make first a release with the new features compatible with older OCaml versions, and then a minor release that adds nothing but the 4.06 support, so that users of either versions can benefit from the other new notty features.)

**Comment by pqwy** [comment]
I'll make a minor that adapts to this. Thanks for the heads-up!

**Comment by gasche** [comment]
Thanks! If that may help, this Changes entry was recently fleshed up by Richard Bonichon to add more porting information:

```
* GPR#615: Format, add symbolic formatters that output symbolic
  pretty-printing items. New fields have been added to the
  formatter_out_functions record, thus this change will break any code building
  such record from scratch.
  When building Format.formatter_out_functions values redefinining the out_spaces field,
  "{ fmt_out_funs with out_spaces = f; }" should be replaced by
  "{ fmt_out_funs with out_spaces = f; out_indent = f; }" to maintain the old behavior.
  (Richard Bonichon and Pierre Weis, review by Alain Frisch)
```

**Comment by pqwy** [comment]
Yeah, just looking through the relevant commits...

Sadly, even though several people are talking about using `{ funs with ... }` construction, I cannot find a handy initial instance of this record, with (e.g.) `out_indent = out_spaces` etc, that I can update into my desired formatter.

Which leaves me with either not supporting < 4.06, or playing tricks with creating a buffer formatter and then replacing almost all, but not really all, of its functions to turn it into something different.

For reference, I am [using these interfaces](https://github.com/pqwy/notty/blob/6f409ed6fb8ea1663deaf6d56011ad789c09548d/src/notty.ml#L425-L445) to effectively obtain a "symbolic formatter" of 4.06.

**Comment by pqwy** [comment]
The sequence
```OCaml
let fmt = make_formatter (fun _ _ -> ignore) ignore in
let fof = pp_get_formatter_out_functions fmt () in
pp_set_formatter_out_functions fmt
  { fof with out_flush; out_string; out_spaces; out_newline };
```
_almost_ works.

Except in 4.06 the default `out_indent` directly calls `display_blanks`, not the formatter's `out_spaces`. So the above uses the custom `out_spaces` for spaces within the line, but dumps space characters at the beginning of the line.

I suppose this is the best that modern science can do...

**Comment by gasche** [comment]
I agree that the change is somewhat disruptive, in that there is no nice preprocessing-free way to easily support both new and old OCaml versions with the same codebase. I don't have good solutions to offer (you might have to deal with a transition period where one or several notty releases come in two versions, one `< 4.06` and one `>= 4.06`).

At least I can propagate the information upstream by adding a pointer to this issue from the relevant discussions.

**Comment by pqwy** [comment]
@gasche Thanks a lot for figuring out that this will impact notty and warning ahead of time!
