### ISSUE TITLE
Structure dumper example

### ISSUE THREAD

**Issue by hcarty** [pqwy/notty#26]
Is the structure dumper demo code available?

**Comment by cfcs** [comment]
Structure dumper?

**Comment by hcarty** [comment]
First animation linked from the README: https://asciinema.org/a/ZIXzn2ZmIxK39qoT3eJla5OyO

**Comment by cfcs** [comment]
Oh, that looks neat!

I think you're better off writing David an email, he's usually not using Github very often.

**Comment by hcarty** [comment]
Will do, thanks!
