### ISSUE TITLE
API addition/change

### ISSUE THREAD

**Issue by rneswold** [pqwy/notty#7]
First of all, let me say that `notty` is very nice to use and the result are terrific! Thank you for making this library.

After using it on a few projects, this request came to me.

In the "Additional Combinators" section, there's a function called `tile` which lays out images in a grid. I would recommend renaming it to `grid`, since it defines a finite grid. Next, I request that in the "Primitives" section, you add a function called `tile`:

    val tile : image -> image

which takes an image and infinitely tiles it vertically and horizontally. You use a cropping function to limit the tiling.

I don't know how easy/difficult this would be to implement. I may take a crack at implementing myself, if you think it'd be a good addition to the library.

**Comment by rneswold** [comment]
Actually, `tile` could be more generalized like this:

    val tile : ?col_offset : int -> ?row_offset -> image -> image

where both `col_offset` and `row_offset` default to 0. The offsets indicate the position inside the tile to start at the upper left corner of the clipping region.

**Comment by pqwy** [comment]
I do have an idea how to do `tile`, but I'm not convinced it's not gratuitous. So far I've _removed_ stuff from the lib to make it as compact as possible. Can you describe your use-cases in more detail?

**Comment by pqwy** [comment]
.... in fact, it would break the model in a surprising number of ways. What's `width (tile img)`? If the tiling is infinite upwards and to the left, offsets must be baked into the primitive, as otherwise there is no way to shift such an image. And presumably, `tile a <|> tile b == tile a`? It sounds like such images fail to compose uniformly.

So this would either create a completely separate class of images which behave in a different way, or the core semantics would have to be redefined along the lines of [vg](https://github.com/dbuenzli/vg).

But I'm still curious, which kinds of problems do you think `tile` is a good solution to?

**Comment by rneswold** [comment]
> .... in fact, it would break the model in a surprising number of ways. What's `width (tile img)`?

Good point. Maybe `Invalid_argument`?

The use-case I was thinking about was: if someone wanted a background texture (like in your Game of Life demo) rather than have the program calculate the number of horizontal and vertical repetitions needed for the current screen size, it could just infinitely tile it and cropping to the screen would keep it finite. Changing the starting offsets would allow it to be "animated".

I've used Daniel Bünzli's `vg` library (an OCaml declarative graphics package.) He uses infinite primitives which have to be clipped to be usefully rendered. So I was in that frame of mind when I thought of it.

**Comment by pqwy** [comment]
> Good point. Maybe `Invalid_argument`?

`-1/12`!

> The use-case I was thinking about was: if someone wanted a background texture [...]

Yeah, I thought that would be the use-case.

`life`, as an API demo, uses the simplest possible approach. A different way to make it is to compute the core cell, tile it to something fairly large, retain that image, and crop it cyclically in the step number.

VG-style semantics is super-neat, but it's an all-or-nothing thing. Adding some infinitary images partitions image space into images that work well, and images that work well in a completely different way. I don't want a mix of the two.

But it _is_ an appealing alternate API... :smile:
