### ISSUE TITLE
Merging attributes

### ISSUE THREAD

**Issue by rneswold** [pqwy/notty#8]
It would be nice, when overlaying one image on another, that if the upper image doesn't specify a background, it uses the lower image's background. Right now, it seems the upper image will have a black background (unless I missed an important operator or combinator.) Maybe a new operator `<//>` to overlay and blend the two images?

Something like that would make it easy to do things like:

```
open Notty
open Notty.Infix

let progress_bar w pcnt =
  let pcnt = max 0.0 (min 1.0 pcnt) in
  let w' = truncate (float w *. pcnt) in
  I.(hsnap w (strf ~attr:A.(fg yellow) "%.0f%%" (pcnt *. 100.))) </>
    I.((char A.(bg cyan) ' ' w' 1) <|> (char A.(bg blue) ' ' (w - w') 1))
```

The progress is displayed using the background attribute. I'd like it to continue behind the numeric string but, instead, the background of the text is always black. And it's not necessarily easy to implement what I want using the current combinators. I'd have to keep the string and conditionally cut it up so half can be displayed with one background the other half with the other background. I'd also have to stop using `hsnap` since I'd have to carefully control how it's centered to make sure the backgrounds lined up properly.

**Comment by rneswold** [comment]
A more formal way to say it might be:

> When blending two images, the top image's contents and attributes are used. If the top image is missing an attribute (a foreground and/or background attribute), then the lower image's corresponding attribute is used.

**Comment by hannesm** [comment]
If I understand you correctly, you want to have support for a `transparent` (or void) colour (if used on an overlay, the underlying colour is used)?

**Comment by pqwy** [comment]
This has to do with something I wanted to write on #7, which is that in principle, I'm reluctant to add more abstraction mechanisms which are paralleled by functions. So the first time around, I didn't want to have images _open_ in the attribute.

But early on, `notty` did have this feature, of influencing the attributes of a constructed image, and I'm increasingly convinced this is useful. It's still a bit unclear what's the most compact system of describing that, but I'm planning something like that for the next release.

**Comment by rneswold** [comment]
The base attribute is `empty`. You build your attributes by appending foreground and background colors and text styles. I guess I'm saying that `A.empty` should be equivalent to `A.(fg transparent ++ bg transparent)`, if `transparent` was a color defined in the library.

**Comment by rneswold** [comment]
Let #24 handle this issue.
